//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from highc.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IhighcListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class highcBaseListener : IhighcListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] highcParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] highcParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.top_level_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_level_statement([NotNull] highcParser.Top_level_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.top_level_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_level_statement([NotNull] highcParser.Top_level_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.mod_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMod_statement([NotNull] highcParser.Mod_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.mod_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMod_statement([NotNull] highcParser.Mod_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.use_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUse_statement([NotNull] highcParser.Use_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.use_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUse_statement([NotNull] highcParser.Use_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.template_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplate_header([NotNull] highcParser.Template_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.template_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplate_header([NotNull] highcParser.Template_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.struct_define_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_define_field([NotNull] highcParser.Struct_define_fieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.struct_define_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_define_field([NotNull] highcParser.Struct_define_fieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.struct_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_define([NotNull] highcParser.Struct_defineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.struct_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_define([NotNull] highcParser.Struct_defineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.fn_define_argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFn_define_argument([NotNull] highcParser.Fn_define_argumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.fn_define_argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFn_define_argument([NotNull] highcParser.Fn_define_argumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.fn_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFn_define([NotNull] highcParser.Fn_defineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.fn_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFn_define([NotNull] highcParser.Fn_defineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.alias_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlias_define([NotNull] highcParser.Alias_defineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.alias_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlias_define([NotNull] highcParser.Alias_defineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] highcParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] highcParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] highcParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] highcParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_statement([NotNull] highcParser.Return_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_statement([NotNull] highcParser.Return_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.defer_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefer_statement([NotNull] highcParser.Defer_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.defer_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefer_statement([NotNull] highcParser.Defer_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] highcParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] highcParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.if_tail_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_tail_statement([NotNull] highcParser.If_tail_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.if_tail_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_tail_statement([NotNull] highcParser.If_tail_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_statement([NotNull] highcParser.While_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_statement([NotNull] highcParser.While_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.assign_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign_statement([NotNull] highcParser.Assign_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.assign_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign_statement([NotNull] highcParser.Assign_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.let_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLet_expression([NotNull] highcParser.Let_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.let_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLet_expression([NotNull] highcParser.Let_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.let_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLet_statement([NotNull] highcParser.Let_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.let_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLet_statement([NotNull] highcParser.Let_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.typename_fn_args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypename_fn_args([NotNull] highcParser.Typename_fn_argsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.typename_fn_args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypename_fn_args([NotNull] highcParser.Typename_fn_argsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypenameMany</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypenameMany([NotNull] highcParser.TypenameManyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypenameMany</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypenameMany([NotNull] highcParser.TypenameManyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypenameGeneric</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypenameGeneric([NotNull] highcParser.TypenameGenericContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypenameGeneric</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypenameGeneric([NotNull] highcParser.TypenameGenericContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypenameFn</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypenameFn([NotNull] highcParser.TypenameFnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypenameFn</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypenameFn([NotNull] highcParser.TypenameFnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypenameArray</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypenameArray([NotNull] highcParser.TypenameArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypenameArray</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypenameArray([NotNull] highcParser.TypenameArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypenameSingle</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypenameSingle([NotNull] highcParser.TypenameSingleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypenameSingle</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypenameSingle([NotNull] highcParser.TypenameSingleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypenamePointer</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypenamePointer([NotNull] highcParser.TypenamePointerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypenamePointer</c>
	/// labeled alternative in <see cref="highcParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypenamePointer([NotNull] highcParser.TypenamePointerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] highcParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] highcParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddExpression([NotNull] highcParser.AddExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddExpression([NotNull] highcParser.AddExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicExpression([NotNull] highcParser.LogicExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicExpression([NotNull] highcParser.LogicExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MemoryExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemoryExpression([NotNull] highcParser.MemoryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MemoryExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemoryExpression([NotNull] highcParser.MemoryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] highcParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] highcParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CompareExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompareExpression([NotNull] highcParser.CompareExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CompareExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompareExpression([NotNull] highcParser.CompareExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CallExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallExpression([NotNull] highcParser.CallExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CallExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallExpression([NotNull] highcParser.CallExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulExpression([NotNull] highcParser.MulExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulExpression([NotNull] highcParser.MulExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BitwiseExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitwiseExpression([NotNull] highcParser.BitwiseExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BitwiseExpression</c>
	/// labeled alternative in <see cref="highcParser.op_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitwiseExpression([NotNull] highcParser.BitwiseExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.explicit_template_instantiation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicit_template_instantiation([NotNull] highcParser.Explicit_template_instantiationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.explicit_template_instantiation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicit_template_instantiation([NotNull] highcParser.Explicit_template_instantiationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.call_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_expression([NotNull] highcParser.Call_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.call_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_expression([NotNull] highcParser.Call_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.struct_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_expression([NotNull] highcParser.Struct_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.struct_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_expression([NotNull] highcParser.Struct_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.struct_expression_set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_expression_set([NotNull] highcParser.Struct_expression_setContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.struct_expression_set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_expression_set([NotNull] highcParser.Struct_expression_setContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.dot_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDot_expression([NotNull] highcParser.Dot_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.dot_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDot_expression([NotNull] highcParser.Dot_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.term_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm_expression([NotNull] highcParser.Term_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.term_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm_expression([NotNull] highcParser.Term_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] highcParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] highcParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="highcParser.boolean_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_literal([NotNull] highcParser.Boolean_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="highcParser.boolean_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_literal([NotNull] highcParser.Boolean_literalContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
